#!/bin/bash

# Variables
osxversion=`sw_vers -productVersion | awk '{print $1}'`

# Snow Leopard
if [[ "$osxversion" == *10.6* ]]
	then
		echo "***** Setting Firmware Password.....*****"
		echo ""
		echo "Please enter the password for hisdadmin..."
		sudo /usr/libexec/setregproptool -m command -p 'v&ZAC9ax' -o 'v&ZAC9ax'
		echo "***** Setting Firmware Password - Done! *****"
		echo ""
fi

# Lion
if [[ "$osxversion" == *10.7* ]]
	then
		echo "***** Setting Firmware Password.....*****"
		echo ""
		echo "Please enter the password for hisdadmin..."
		sudo /usr/libexec/setregproptool -m command -p 'v&ZAC9ax' -o 'v&ZAC9ax'
		echo "***** Setting Firmware Password - Done! *****"
		echo ""
fi

# Mountain Lion
if [[ "$osxversion" == *10.8* ]]
	then
		echo "***** Setting Firmware Password.....*****"
		echo ""
		echo "Please enter the password for hisdadmin..."
		sudo /usr/libexec/setregproptool -m command -p 'v&ZAC9ax' -o 'v&ZAC9ax'
		echo "***** Setting Firmware Password - Done! *****"
		echo ""
fi

# Mavericks
if [[ "$osxversion" == *10.9* ]]
	then
		echo "***** Setting Firmware Password.....*****"
		echo ""
		echo "Please enter the password for hisdadmin..."
		sudo /usr/local/setregproptool/setregproptool -m command -p 'v&ZAC9ax' -o 'v&ZAC9ax'
		echo "***** Setting Firmware Password - Done! *****"
		echo ""
fi

# Yosemite
if [[ "$osxversion" == *10.10* ]]
	then
		echo "***** Setting Firmware Password.....*****"
		echo ""
		echo "Please enter the password for hisdadmin..."
		sudo /usr/local/setregproptool/setregproptool -m command -p 'v&ZAC9ax' -o 'v&ZAC9ax'
		echo "***** Setting Firmware Password - Done! *****"
		echo ""
fi

# El Capitan
if [[ "$osxversion" == *10.11* ]]
	then
		echo "***** Setting Firmware Password.....*****"
		echo ""
		echo "Please enter the password for hisdadmin..."
		sudo /usr/local/setregproptool/setregproptool -m command -p 'v&ZAC9ax' -o 'v&ZAC9ax'
		echo "***** Setting Firmware Password - Done! *****"
		echo ""
fi

exit 0
