#!/bin/sh

# Variables
osxversion=`sw_vers -productVersion | awk '{print $1}'`
username=`whoami`
# ipAddress="10.255.149.11"
# nbiName="DSR-10.10.nbi"
# dmgName="NetInstall.dmg"

# Easy NetBoot
# bless --verbose --netboot --server bsdp://${ipAddress}
# bless --verbose --netboot --server bsdp://10.255.149.11
# bless --verbose --netboot --booter tftp://${ipAddress}/NetBoot/NetBootSP0/${nbiName}/i386/booter --kernelcache tftp://${ipAddress}/NetBoot/NetBootSP0/${nbiName}/i386/x86_64/kernelcache --options 'rp=http://${ipAddress}/NetBoot/NetBootSP0/${nbiName}/${dmgName}' --nextonly

if [[ "$username" == *hisdadmin* ]]
	then
		echo "Please enter the password for hisdadmin..."
	else
		echo "Please enter the password for the administrator account you are currently logged into..."
fi

# Leopard
if [[ "$osxversion" == *10.5* ]]
	then
		sudo bless --verbose --netboot \
		--booter tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/booter \
		--kernel tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/mach.macosx \
		--options rp=http://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/NetInstall.sparseimage \
		--nextonly
		sudo shutdown -r now
#		sudo bless --netboot \
#		   --booter tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/booter \
#		   --kernel tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/x86_64/kernelcache \
#		   --options rp=http://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/NetInstall.sparseimage
#		sudo nvram "$( sudo nvram efi-boot-file \
#		   | sed -E 's/^efi-boot-file[[:space:]]*/efi-boot-kernelcache=/' )"
#		sudo nvram -d efi-boot-file
#		sudo shutdown -r now
fi

# Snow Leopard
if [[ "$osxversion" == *10.6* ]]
	then
		sudo bless --verbose --netboot \
		--booter tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/booter \
		--kernel tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/mach.macosx \
		--options rp=http://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/NetInstall.sparseimage \
		--nextonly
		sudo shutdown -r now
#		sudo bless --netboot \
#		   --booter tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/booter \
#		   --kernel tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/x86_64/kernelcache \
#		   --options rp=http://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/NetInstall.sparseimage
#		sudo nvram "$( sudo nvram efi-boot-file \
#		   | sed -E 's/^efi-boot-file[[:space:]]*/efi-boot-kernelcache=/' )"
#		sudo nvram -d efi-boot-file
#		sudo shutdown -r now
fi

# Lion
if [[ "$osxversion" == *10.7* ]]
	then
		sudo bless --verbose --netboot \
		--booter tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/booter \
		--kernelcache tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/i386/x86_64/kernelcache \
		--options 'rp=http://10.255.149.11/NetBoot/NetBootSP0/DSR-10.7.nbi/NetInstall.dmg' \
		--nextonly
		sudo shutdown -r now
fi

# Mountain Lion
if [[ "$osxversion" == *10.8* ]]
	then
		sudo bless --verbose --netboot \
		--booter tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/i386/booter \
		--kernelcache tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/i386/x86_64/kernelcache \
		--options 'rp=http://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/NetInstall.dmg' \
		--nextonly
		sudo shutdown -r now
fi

# Mavericks
if [[ "$osxversion" == *10.9* ]]
	then
		sudo bless --verbose --netboot \
		--booter tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/i386/booter \
		--kernelcache tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/i386/x86_64/kernelcache \
		--options 'rp=http://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/NetInstall.dmg' \
		--nextonly
		sudo shutdown -r now
fi

# Yosemite
if [[ "$osxversion" == *10.10* ]]
	then
		sudo bless --verbose --netboot \
		--booter tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/i386/booter \
		--kernelcache tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/i386/x86_64/kernelcache \
		--options 'rp=http://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/NetInstall.dmg' \
		--nextonly
		sudo shutdown -r now
fi

# El Capitan
if [[ "$osxversion" == *10.11* ]]
	then
		sudo bless --verbose --netboot \
		--booter tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/i386/booter \
		--kernelcache tftp://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/i386/x86_64/kernelcache \
		--options 'rp=http://10.255.149.11/NetBoot/NetBootSP0/DSR-10.11.nbi/NetInstall.dmg' \
		--nextonly
		sudo shutdown -r now
fi
