#!/bin/bash

# Determine OS version
osvers=$(sw_vers -productVersion | awk -F. '{print $2}')

# Lion or higher 
if [[ ${osvers} -ge 7 ]]; then
		echo "Removing HISD-secure Wireless Profile..."
		echo "Please enter the password for hisdadmin..."
		sudo /usr/bin/profiles -R -p org.houstonisd.profile.hisdsecure
		sudo /bin/rm -f /var/hisd/hisdprofiles/HISD-Secure.mobileconfig
		sudo /usr/sbin/pkgutil --forget org.houstonisd.HISD-Secure
		echo "Removing HISD-secure Wireless Profile...Done!"
fi

exit 0
