#!/bin/bash

# Determine OS version
osvers=$(sw_vers -productVersion | awk -F. '{print $2}')
udn="csradda"
password="*ik,.lo("

if [[ ${osvers} -ge 7 ]]; then
	echo "\033[1m\033[93m***** Unbinding Mac from AD..... *****\033[0m"
	# Attempt a sane unbind first.
	echo "Please enter the password for hisdadmin..."
	sudo /usr/sbin/dsconfigad -remove -username $udn -password "$password"
	sleep 3

	# Force unbind anyway just in case the regular unbind doesn't work.
	sudo /usr/sbin/dsconfigad -force -remove -user ADqwerty -password 12345
	sleep 3

	sudo /usr/bin/killall opendirectoryd
	echo "\033[1m\033[93m***** Unbinding Mac from AD DONE!!! *****\033[0m"

	echo "\033[1m\033[93m***** Cleaning up AD-related preferences... *****\033[0m"
	sudo /bin/rm -rf /Library/Keychains/System.keychain 
	sudo /bin/rm -rf /Library/Preferences/OpenDirectory/*
	sudo /bin/rm -rf /etc/krb5.keytab 
	sudo /bin/rm -rf /var/db/dslocal/nodes/Default/config/*
	sudo /bin/rm -rf /var/db/krb5kdc/*
	sudo /usr/bin/killall opendirectoryd
	echo "\033[1m\033[93m***** AD Preferences Clean-up DONE!!! *****\033[0m"
	echo "\033[1m\033[91m***** Please reboot the Mac before attempting to re-bind to AD *****\033[0m"
fi

exit 0
