#!/bin/bash

# Determine OS version
osvers=$(sw_vers -productVersion | awk -F. '{print $2}')

# Lion or higher 
if [[ ${osvers} -ge 7 ]]; then
		echo "Please ensure there is a wired connection to the machine"
		echo "Running Managed Software Center in Automatic Mode....."
		echo "This will also install any pending software for this machine"
		echo "Please enter the password for hisdadmin..."
		sudo /usr/local/munki/managedsoftwareupdate --auto
fi

exit 0
